# Generated by Django 2.2.5 on 2021-09-05 01:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20210905_0127'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='autor',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='cuerpo',
            new_name='body',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='categoría',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='título',
            new_name='title',
        ),
    ]
