# Generated by Django 2.2.5 on 2021-09-06 20:53

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20210905_0132'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='prev',
            field=ckeditor.fields.RichTextField(blank=True, max_length=255, null=True),
        ),
    ]
