# Generated by Django 2.2.5 on 2021-09-08 00:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20210907_1518'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('name',), 'verbose_name': 'categoría', 'verbose_name_plural': 'categorías'},
        ),
    ]
